# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-19 03:35
from __future__ import unicode_literals

import DjangoUeditor.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户文章')),
                ('title', models.CharField(max_length=200, verbose_name='用户文章')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='文章内容')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='写文章时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改文章时间')),
                ('count', models.IntegerField(default=0, verbose_name='点击量')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Car_name', models.CharField(max_length=200, verbose_name='汽车品牌')),
                ('Car_model', models.CharField(max_length=200, verbose_name='汽车型号')),
                ('Car_power', models.CharField(max_length=200, verbose_name='汽车动力')),
                ('Car_description', DjangoUeditor.models.UEditorField(verbose_name='汽车描述')),
                ('Car_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户主键')),
                ('nickname', models.CharField(max_length=100, verbose_name='用户昵称')),
                ('avatar', models.ImageField(default='static/img/avatar/default.jpg', upload_to='static/img/avatar', verbose_name='用户头像')),
                ('gender', models.CharField(default='男', max_length=10, verbose_name='用户性别')),
                ('age', models.IntegerField(default='18', max_length=20, verbose_name='用户年龄')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
